language: python
dist: xenial
python:
- 3.5
- 3.6
- 3.7
install:
- pip install -r requires/development.txt codecov
script:
- nosetests --with-coverage
- python setup.py build_sphinx
after_success:
- codecov
sudo: false
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: sprockets
  password:
    secure: ARvFw5CHqQZqPOkJXxQSe7EAEbX1yt7FiBTtzz8Gd6XndbY10HVCSWhGYeldm9LevvQc9p77pBEvsl+bXGQbJ3NW/r/U5PADaFdmi4bxmXN8yc+dFKzn72MpZfL+kCV2T/HutuOY6dQa4okTkKVV+sqwPLKPhL69zH/PxQg8qe4=
  on:
    python: 3.7
    tags: true
    all_branches: true
